import os
import glob
import numpy as np
import pandas as pd

base_directory = "/Users/JB/Rotation_bkslab/250130_chaifold" #in this location, there are lots of subdirectories with .out suffix
output_file = "/Users/JB/Rotation_bkslab/250130_chaifold/chai_scores_idx_0.xlsx" #different Chai-1 scores are stored in this new excel file.

out_folders = [folder for folder in glob.glob(os.path.join(base_directory, "*.out")) if os.path.isdir(folder)]

data_list = []

for out_folder in out_folders:
    npz_file_path = os.path.join(out_folder, "scores.model_idx_0.npz") #.npz file is generated by Chai-1 in each .out folder
    data = np.load(npz_file_path)

    aggregate_score = data.get('aggregate_score', np.nan)
    iptm = data.get('iptm', np.nan)
    ptm = data.get('ptm', np.nan)
    per_chain_ptm = data.get('per_chain_ptm', np.nan)
    per_chain_pair_iptm = data.get('per_chain_pair_iptm', np.nan)
    has_inter_chain_clashes = data.get('has_inter_chain_clashes', np.nan)
    chain_chain_clashes = data.get('chain_chain_clashes', np.nan)

    data_list.append({
        "Index": os.path.basename(out_folder),
        "Aggregate Score": aggregate_score,
        "iPTM": iptm,
        "pTM": ptm,
        "pTM per chain": per_chain_ptm,
        "iPTM per chain pair": per_chain_pair_iptm,
        "Interchain clash?": has_inter_chain_clashes,
        "Matrix chain-chain clashes": chain_chain_clashes
    })

Chai_output_scores = pd.DataFrame(data_list)
Chai_output_scores.to_excel(output_file, index=False)